### ISSUE TITLE
Googleの検索に引っかかるようにする

### ISSUE THREAD

**Issue by narugit** [nextandot/nextandot.github.io#2]

**Comment by narugit** [comment]
- https://nextandot.github.io/sitemap.xml
- https://nextandot.github.io/robots.txt

アクセスできるようになった

**Comment by narugit** [comment]
あとはsitemap.xmlのURLをGoogle Search Consoleに登録すればOK
が、我々が所有者であることを示すために、ドメインを取得する必要がある。

**Comment by youseegreen** [comment]
### 登録手順
1. 該当Google Accountにログインした状態でGoogle Search Consoleに入る
2. URLプレフィックスを選択し、https://nextandot.github.io を指定
3. 所有権の確認方法として、1個目の「htmlをダウンロードしてhttps://nextandot.github.io/ 配下にそのファイルを設置する」を選択
4. 実際に3.の処理を実施すると無事所有権を確認できた。
5. 左のメニュー欄からサイトマップをクリック
6. サイトマップのURLにsitemap.xml を指定し送信 → 無事成功
7. 左のメニュー欄からURL検査をクリックし、https://nextandot.github.io/ で検索
8. インデックス登録をリクエストボタンを押して待つ

**Comment by narugit** [comment]
検索引っかかるようになったため、closeする

https://nextandot.slack.com/archives/CJLKRRXQS/p1726385316327119
